version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: beautifulsoup4
    versions:
    - "< 4.6.2"
    - ">= 4.6.1.a"
