# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  apt_packages:
    - libxml2-dev
    - libxslt-dev
    - libssl-dev
    - openssl
    - libcurl4-openssl-dev
  jobs:
    post_install:
      # Use job hooks so we can specify the `--no-binary` option, which is not
      # possible in the `python.install` section of this config file.
      - python -m pip install '.[server,docs]' --no-binary lxml --upgrade --upgrade-strategy only-if-needed
      # Experimental dependencies are not supported in standard package
      # metadata, so we need to pip install them directly.
      - python -m pip install --exists-action=w -r requirements-experimental.txt

sphinx:
  configuration: docs/source/conf.py

formats: all
